# Generated by Django 5.1.6 on 2025-04-18 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosDeleteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField()),
                ('operation_type', models.CharField(default='DELETE', max_length=10)),
                ('operation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation_user', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Log de Eliminaciones',
                'verbose_name_plural': 'Logs de Eliminaciones',
            },
        ),
        migrations.CreateModel(
            name='UsuariosUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('changed_fields', models.JSONField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('operation_type', models.CharField(default='UPDATE', max_length=10)),
                ('operation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation_user', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Log de Actualizaciones',
                'verbose_name_plural': 'Logs de Actualizaciones',
            },
        ),
        migrations.CreateModel(
            name='UsuariosInsertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField()),
                ('operation_type', models.CharField(default='INSERT', max_length=10)),
                ('operation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation_user', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Inserciones',
                'verbose_name_plural': 'Logs de Inserciones',
            },
        ),
    ]
